# Generated by Django 4.2.1 on 2023-05-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vault_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
