# Generated by Django 4.2.1 on 2023-05-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_profile_vault_unlocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='vault_unlocked',
            new_name='vault_locked',
        ),
    ]
