# Generated by Django 4.2.1 on 2023-05-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_rename_vault_unlocked_profile_vault_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vault_locked',
            field=models.BooleanField(default=True),
        ),
    ]
